const constants = {
    APISTATUS: 'APISTATUS',
    CHANGE_NAME: 'CHANGE_NAME',
    RECEIVE_DASHBOARD_CONFIG_DATA: 'RECEIVE_DASHBOARD_CONFIG_DATA',
    GLOBAL_FILTER: 'GLOBAL_FILTER',
    DEMAND_AND_COLLECTION: 'DEMAND_AND_COLLECTION',
    GLOBAL_FILTER_DATA: 'GLOBAL_FILTER_DATA',
    CHARTS: 'CHARTS',
    LANGUAGE_CHANGE: 'LANGUAGE_CHANGE',
    FILE_UPLOAD: 'FILE_UPLOAD',
    S3_IMAGE: 'S3_IMAGE',
    MDMS: 'MDMS'
}

export default constants