export const SET_ROUTE = "SET_ROUTE";
export const TOGGLE_SPINNER = "TOGGLE_SPINNER";
export const GENERAL_MDMS_FETCH_SUCCESS = "GENERAL_MDMS_FETCH_SUCCESS";
export const GENERAL_MDMS_FETCH_ERROR = "GENERAL_MDMS_FETCH_ERROR";
